name: build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch dependencies
        run: |
          sudo apt-get install freeglut3-dev
          sudo apt-get install libglew-dev

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..
        
      - name: Build
        run: |
          cd build
          make

  macOS:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch dependencies
        run: |
          brew install freeglut
          brew install glew

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..
        
      - name: Build
        run: |
          cd build
          make

  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..
        
      - name: Build
        run: |
          cd build
          cmake --build . --config Release
